# Generated by Django 4.2.2 on 2023-06-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_rename_uuid_product_product_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_uuid',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_uuid',
            new_name='uuid',
        ),
    ]
