# Generated by Django 4.2.2 on 2023-06-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_rename_uuid_product_product_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='Store.product'),
        ),
    ]
