# Generated by Django 4.2.2 on 2023-07-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_alter_store_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.CheckConstraint(check=models.Q(('store_name', ''), _negated=True), name='store_name_not_empty'),
        ),
    ]
