# Generated by Django 4.2.2 on 2023-07-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_remove_product_name_not_empty_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='name_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='store',
            name='store_name_not_empty',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.CheckConstraint(check=models.Q(('store_name', ''), _negated=True), name='store_name_not_empty'),
        ),
    ]
