# Generated by Django 4.2.2 on 2023-06-15 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
        ('Material', '0002_remove_material_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Material_Quantity',
            new_name='MaterialQuantity',
        ),
        migrations.RenameModel(
            old_name='Material_Stock',
            new_name='MaterialStock',
        ),
    ]
