# Generated by Django 4.2.2 on 2023-06-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0004_material_uuid_materialquantity_uuid_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='materialstock',
            constraint=models.CheckConstraint(check=models.Q(('current_capacity__lte', models.F('max_capacity'))), name='current_capacity_lte_max_capacity'),
        ),
    ]
