# Generated by Django 4.2.2 on 2023-06-22 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0005_materialstock_current_capacity_lte_max_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='uuid',
            new_name='material_uuid',
        ),
        migrations.RenameField(
            model_name='materialquantity',
            old_name='uuid',
            new_name='material_quantity_uuid',
        ),
        migrations.RenameField(
            model_name='materialstock',
            old_name='uuid',
            new_name='material_stock_uuid',
        ),
    ]
