# Generated by Django 4.2.2 on 2023-06-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0007_rename_material_uuid_material_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='uuid',
            new_name='material_uuid',
        ),
        migrations.RenameField(
            model_name='materialquantity',
            old_name='uuid',
            new_name='material_quantity_uuid',
        ),
        migrations.RenameField(
            model_name='materialstock',
            old_name='uuid',
            new_name='material_stock_uuid',
        ),
    ]
