# Generated by Django 4.2.2 on 2023-07-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0009_alter_material_name_material_material_name_not_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
