# Generated by Django 4.2.2 on 2023-07-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0011_remove_material_material_name_not_empty_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='material',
            name='material_name_not_empty',
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='material_name_not_empty'),
        ),
    ]
