# Generated by Django 4.2.2 on 2023-07-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0013_materialquantity_quantity_greater_gte_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0.01)), name='material_price_gte_0.01'),
        ),
    ]
